export enum QuickAction {
  CHECK_ALL_QUESTIONMARK_PANELS = 'CHECK_ALL_QUESTIONMARK_PANELS',
  UNCHECK_ALL_QUESTIONMARK_PANELS = 'UNCHECK_ALL_QUESTIONMARK_PANELS',
  CHECK_ALL_PEACH_MEDALLIONS = 'CHECK_ALL_PEACH_MEDALLIONS',
  UNCHECK_ALL_PEACH_MEDALLIONS = 'UNCHECK_ALL_PEACH_MEDALLIONS',
  CHECK_ALL_P_SWITCHES = 'CHECK_ALL_P_SWITCHES',
  UNCHECK_ALL_P_SWITCHES = 'UNCHECK_ALL_P_SWITCHES',
  RESET = 'RESET',
}
