export const CONSTANTS = {
  STORAGE_KEY_SETTINGS: 'mkworld-settings',
  STORAGE_KEY_CHECKLIST_MODELS: 'mkworld-checklist-models',
  STORAGE_KEY_ACHIEVEMENTS: 'mkworld-achievements',
  STICKERS_PER_PAGE: 32,
  STICKERS_PER_ROW: 8,
  STICKERS_PER_COLUMN: 4,
  QUAD_TREE_THRESHOLD: 300,
  QUAD_TREE_DEBOUNCE_TIME: 200,
  QUAD_TREE_VISIBLE_BUFFER: 3,
  QUAD_TREE_MAX_OBJECTS: 10,
  MAP_DRAG_THRESHOLD: 5,
  STICKER_ALBUM_DRAG_THRESHOLD: 20,
};
