export const CONSTANTS = {
  STORAGE_KEY_SETTINGS: 'mkworld-settings',
  STORAGE_KEY_CHECKLIST_MODELS: 'mkworld-checklist-models',
  STORAGE_KEY_ACHIEVEMENTS: 'mkworld-achievements',
  STICKERS_PER_PAGE: 32,
  STICKERS_PER_ROW: 8,
  STICKERS_PER_COLUMN: 4,
  QUADTREE_THRESHOLD: 100,
  QUADTREE_DEBOUNCE_TIME: 200,
  QUADTREE_VISIBLE_BUFFER: 2,
};
